name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: ng build --configuration=production

      - name: Deploy to Nginx
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NGINX_HOST }}
          username: ${{ secrets.NGINX_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/browser/*"
          target: "/var/www/html/todo-app"
