name: Angular CI/CD

on:
  push:
    branches:
      - main  # Adjust this based on your branch name

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:            
            node-version: '20'

        - name: Install dependencies
          run: npm install

        - name: Build
          run: npm run build --prod

        - name: Configure SSH
          run: |
            mkdir -p ~/.ssh/
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.NGINX_HOST }} >> ~/.ssh/known_hosts

        # - name: Deploy to Nginx
        #   uses: appleboy/scp-action@master
        #   with:
        #     host: ${{ secrets.NGINX_HOST }}
        #     username: ${{ secrets.NGINX_USERNAME }}
        #     password: ${{ secrets.NGINX_PASSWORD }}
        #     source: "dist/*"
        #     target: "/var/www/angular-app"
    deploy:
        runs-on: ubuntu-latest
        needs: [build]
        environment:
            name: production
        steps:
            - name: Deploy to Nginx
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.NGINX_HOST }}
                username: ${{ secrets.NGINX_USERNAME }}
                password: ${{ secrets.NGINX_PASSWORD }}
                source: "dist/browser/*"
                target: "/var/www/html/todo-app"
                
